### ISSUE TITLE
Option to concatenate files

### ISSUE THREAD

**Issue by pzuraq** [broccolijs/broccoli-merge-trees#17]
I am currently trying to solve an issue where I am merging trees with files that have the same name and should be concatenated rather than overwritten. There are concat plugins for broccoli, but it seems like overkill for this use case. Since mergeTrees already has an option to overwrite files, would it make sense to have an option to concatenate the files as well?

**Comment by joliss** [comment]
This is out of scope for merge-trees, but I also don't know any plugin that can do that. Perhaps you'd have to write a new plugin.

**Comment by pzuraq** [comment]
No problem, I'll find an alternative.
