### ISSUE TITLE
ENOTDIR bug?

### ISSUE THREAD

**Issue by BryanCrotaz** [broccolijs/broccoli-merge-trees#23]
Seeing the below error on Windows, and npm cache clean etc doesn't fix it.

You can reproduce by running `ember build` on https://github.com/shaunc/ember-grid/commit/edaddd73459494097498045ddc01d289567b3229

Is this a known bug?

```
Build failed.
ENOTDIR, not a directory 'G:\Projects\ember-grid\tmp\broccoli_merge_trees-input_
base_path-IfcH4Dsc.tmp\1'
Error: ENOTDIR, not a directory 'G:\Projects\ember-grid\tmp\broccoli_merge_trees
-input_base_path-IfcH4Dsc.tmp\1'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at G:\Projects\ember-grid\node_modules\ember-cli\node_modules\broccoli-merge
-trees\index.js:35:19
    at Array.map (native)
    at mergeRelativePath (G:\Projects\ember-grid\node_modules\ember-cli\node_mod
ules\broccoli-merge-trees\index.js:33:28)
    at BroccoliMergeTrees.build (G:\Projects\ember-grid\node_modules\ember-cli\n
ode_modules\broccoli-merge-trees\index.js:26:3)
    at G:\Projects\ember-grid\node_modules\ember-cli\node_modules\broccoli-merge
-trees\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (G:\Projects\ember-grid\node_modules\ember-c
li\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (G:\Projects\ember-grid\node_modules\e
mber-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (G:\Projects\ember-grid\node_modules\ember-cl
i\node_modules\rsvp\dist\rsvp.js:476:11)
```

**Comment by joliss** [comment]
Can you run `ember server` and look around in the parent directory (`G:\Projects\ember-grid\tmp\broccoli_merge_trees
-input_base_path-IfcH4Dsc.tmp`) and tell us what you see?

**Comment by BryanCrotaz** [comment]
```
G:\Projects\ember-grid\tmp>cd broccoli_merge_trees-input_base_path-804QQxE9.tmp

G:\Projects\ember-grid\tmp\broccoli_merge_trees-input_base_path-804QQxE9.tmp>dir

 Volume in drive G is Backup of raid
 Volume Serial Number is 8A05-BF40

 Directory of G:\Projects\ember-grid\tmp\broccoli_merge_trees-input_base_path-80
4QQxE9.tmp

15/09/2015  23:30    <DIR>          .
15/09/2015  23:30    <DIR>          ..
15/09/2015  23:30    <SYMLINKD>     0 [G:\Projects\ember-grid\tmp\broccoli_merge
_trees-output_path-94OJMVN0.tmp]
15/09/2015  23:30    <SYMLINK>      1 [G:\Projects\ember-grid\node_modules\ember
-collection\node_modules\layout-bin-packer\dist\layout-bin-packer.js]
               1 File(s)              0 bytes
               3 Dir(s)  296,285,908,992 bytes free
```

**Comment by BryanCrotaz** [comment]
PS Hi Jo, long time no see!

**Comment by joliss** [comment]
Haha, didn't notice your username :) - long time no see Bryan, how have you been? Will you make it to EmberCamp?

So it seems that one of the input nodes ("trees") to merge-trees ended up being a file. That's not supposed to happen.

I think I'll put in some code to check for this with the next refactoring. In the meantime... Hm, this is tricky to debug, and our debugging tools are still not terribly great. Maybe some of the Ember CLI folks have an idea.

Does the error still happen?

**Comment by AndyPyeSC** [comment]
I just saw something very similar with a different app.

I noticed the error was occurring in a package listed as a dependency in package.json. That dependency doesn't seem to be needed any more, so I removed it, which fixed the build error.

I then saw the same ENOTDIR error happen inside a second no-longer-required dependency. Removing that from package.json made that error disappear too.

**Comment by BryanCrotaz** [comment]
what were the dependencies you removed, @AndyPyeSC?

**Comment by AndyPyeSC** [comment]
Following what we discussed about your changes to ember-grid, I removed these:

    "ember-list-view": "BryanCrotaz/list-view#Accept_ember-data_items",
    "ember-collection": "shaunc/ember-collection"

**Comment by BryanCrotaz** [comment]
I will try to be at EmberCamp, Jo - but very very busy with client projects. To such an extent that I have 6 client meetings tomorrow!

**Comment by danconnell** [comment]
I'm getting this error caused by ember-cli-sass. Is there any workaround?

**Comment by stefanpenner** [comment]
This one seems to have gone stale, (lots has changed). We are now looking at https://github.com/broccolijs/broccoli-merge-trees/issues/52.

Closing this one, will gladly reopen if it can be demonstrated.
