### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-merge-trees#26]

**Comment by joliss** [comment]
I removed them in 6453ae8.

**Comment by stefanpenner** [comment]
Seems strange to remove, even if something in the future will add them. How do we have assurances that bugfixes/additional pieces of code are viable and dont regress?

**Comment by joliss** [comment]
Maybe we can talk in person later? Happy to elaborate on my weird non-testing strategy. :)

**Comment by joliss** [comment]
I've brought it back in slightly improved fashion. Now without those pesky ad-hoc helpers, thanks to [broccoli-fixture](https://github.com/broccolijs/broccoli-fixture) which does it for us.
