### ISSUE TITLE
Overwrite tree

### ISSUE THREAD

**Issue by broerse** [broccolijs/broccoli-merge-trees#40]
I try to rename and remove some files in the Ember-cli `treeForPublic` hook. I don't 100% understand this and added `return mergeTrees([publicFiles], { overwrite: true });` to: https://github.com/martinic/ember-cli-deploy-build-plus/blob/robots/index.js#L14-L23

but this does not work. `tree` is always undef. The `overwrite: true` does not work. Is there an example that overwrites and perhaps deletes files? Any help is appreciated. See also http://discuss.emberjs.com/t/different-robots-txt-for-production-and-staging/9358/14

**Comment by stefanpenner** [comment]
Overwite is used to inform the merge start to not error on collision.  In your example you are only merging 1 tree. Their cant be a collision with only 1 input tree

**Comment by broerse** [comment]
Can you tel me how to overwrite? I expect to get only the robots.txt for production if I run `ember build -env production` but also get all others in: https://github.com/martinic/ember-cli-deploy-build-plus/tree/robots/tests/dummy/public 

If I write `publicFiles = stew.rename(publicFiles, 'robots-'+ appEnv +'.txt', 'foo.txt');` I get the correct `foo.txt`

**Comment by stefanpenner** [comment]
Stack - Overflow is likely a better place to ask questions, we should keep the issue tracker focused on bugs. If it turns out you are running into a bug, we can reopen the issue.

Please be sure to include a good example of what you are trying to do.

**Comment by broerse** [comment]
Thanks! It is more a Doc thing than a Bug I think. I asked on http://discuss.emberjs.com/t/different-robots-txt-for-production-and-staging/9358/14

**Comment by broerse** [comment]
@stefanpenner Perhaps it is a bug. If I create a public folder in the root off my addon `tree` is not undef. So it seems the tree for `/tests/dummy/public` should be passed but `ember s` build correctly with `/tests/dummy/public` but passes a tree for `/public` to `treeForPublic`

Is it best to post this bug to ember-cli?

**Comment by broerse** [comment]
Worked around this using postBuild: cleanup.  See https://github.com/martinic/ember-cli-deploy-build-plus/blob/master/index.js Still not sure if this a Doc thing or Bug.
