### ISSUE TITLE
Add option to not error on non-existing directories

### ISSUE THREAD

**Issue by rosshadden** [broccolijs/broccoli-merge-trees#41]
It would be useful if there was an option (or even default behavior) with which `merge-trees` would ignore directories that do not exist.

For example, in a `Brocfile` we use for all projects, we use the directories `[ 'lib', 'src', 'test', 'bin', 'bench' ]`.  These are not always applicable to each project, but in an effort to not have to change the `Brocfile` in every project, we are currently writing our own function that returns a merged tree for just the directories that exist.

I think it would make sense if this project supported that kind of a workflow.  Thoughts?

**Comment by stefanpenner** [comment]
> I think it would make sense if this project supported that kind of a workflow. Thoughts?

We have gone back an forth on this in the past. It seems that the general case, empty directories are  valuable and losing them mid-pipeline is surprising and causes issues. (How does one then represent an empty directory?)

Because of this, I suspect we should close.
