### ISSUE TITLE
Broccoli Merge Tree failing on Windows OS

### ISSUE THREAD

**Issue by GramozKrasniqi** [broccolijs/broccoli-merge-trees#42]
This error is comming out when trying to build the EmberCLI app. 
*Ember -v *
version: 1.13.13
node: 4.2.4
npm: 2.14.10
os: win32 x64

EINVAL: invalid argument, symlink 'D:\Workspaces\xxx\xxx\Core
xxx\xxxx\xxx\xxx-client-app\tmp\babel-output_path-oshgWKVn.tmp\xxx-
client-app\tests\integration\app-pods\components\xxxx\xxx\xxxx\component-test.jshint.js' -> 'D:\Workspaces
\xxxxx\xxx\xxx\xxx\xxxx\xxxx\tmp\bro
ccoli_merge_trees-output_path-BeD6edxd.tmp\xxx\tests\integration\app-
pods\components\xxx\xxxx\xxxx\component-test.jshint.js'

Then updated to Ember Cli v2.4.3
ember -v
ember-cli: 2.4.3
node: 4.2.4
os: win32 x64

ember build 
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
Error: EINVAL: invalid argument, symlink 'file path' <- this length is 281 charachters.

Same error as before.

When the path name is more then 260 the error happens which is the max limit of the windows OS.
Is the broccoli not using the libUV beacuse i think that libUV would fix the problem.

**Comment by stefanpenner** [comment]
> Is the broccoli not using the libUV beacuse i think that libUV would fix the problem.

broccoli uses node, node uses libuv.

**Comment by stefanpenner** [comment]
@felixrieseberg maybe you have some insight?

**Comment by GramozKrasniqi** [comment]
i just tried it the fs.writeFile with more than 260 chars and it is not working i guess it will be the same with the other fs functions.

**Comment by felixrieseberg** [comment]
Quick question: Which version of Windows are you using?

**Comment by GramozKrasniqi** [comment]
Win 7 Enterprise Edition and the Build Server should be on Win Server 2010 i think.

**Comment by GramozKrasniqi** [comment]
One solution could have been if the tmp folder from the broccoli build could have been moved upper in the directory tree, i dont know if currently it allows you to do it

**Comment by felixrieseberg** [comment]
:warning: SOLUTION :warning:

Long story short: Windows supports file paths with 32k characters, Win32 doesn't. Fix: Instruct Win32 to suspend path parsing by prefixing the path with a `\\?\`.

Here's a simple test:

```
let longPath = '\\\\?\\C:\\Users\\feriese\\Desktop\\veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylong';
let i = 0;

function makePath() {
    i++;
    if (i === 10) return;

    require('fs').mkdir(longPath, (e) => {
        longPath += '\\veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerylong';
        makePath();
    });
}

makePath();
```

There's no harm in using the prefix on any version of Windows, even for short file paths. @stefanpenner: We could fix this by simply ensuring that all file operations on Windows get the prefix. Also, Windows Redstone (the next major build - the one with bash and stuff) will allow apps to opt-in into long paths and I assume that Node will do that.

**Comment by stefanpenner** [comment]
@felixrieseberg ah very interesting thank you very much. (I would not have found this myself).

Does this mean, that every write/rename/unlink/mkdir path related operation in needs the prefix?

**Comment by felixrieseberg** [comment]
Yessir - a bunch of lower system libraries and languages use it by default, but libuv doesn't - meaning that we'd have to add it here. I can just send @joliss and you a PR if that'd help.

**Comment by stefanpenner** [comment]
@felixrieseberg well if i understand correctly, literally all our FS API need to be abstracted, is that correct?

Seems like maybe we should create a alternative fs module that we start using all over the place?

**Comment by jasnross** [comment]
Having an alternative fs module to handle this seems like a good idea, but also likely a bigger task. The root of the problem seems to be coming from creating symlinks in node-symlink-or-copy, and I haven't seen the problem coming from elsewhere (yet). Would something like the following be acceptable for now? If so I can submit a PR.

https://github.com/jasnross/node-symlink-or-copy/commit/0e4fd177d6fcf0ab9661d2eee622b3abf10e6fa7

We're currently applying this patch manually during our build process and it's working well so far.

**Comment by felixrieseberg** [comment]
Sure, that'd do the trick.

**Comment by stefanpenner** [comment]
sweet!

**Comment by stefanpenner** [comment]
@jasnross could i convince you to submit pr \w test?

**Comment by jasnross** [comment]
Sure thing! Unfortunately I can't get to it right away, but I'll put some tests together and send it over in the next couple days.

**Comment by stefanpenner** [comment]
related: https://github.com/ember-cli/ember-cli/issues/5748

**Comment by stefanpenner** [comment]
should be fixed by: https://github.com/broccolijs/node-symlink-or-copy/pull/21

**Comment by akashmighty** [comment]
I resolved this error as a result of giving super user access to the command thereby it was able to create the tmp folder as is required.
