### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by khirakawa** [broccolijs/broccoli-merge-trees#44]
The documentation reads: 

```
The structure of output.js will be as follows:

// - header
// - ordered content of the files in headerFiles
// - un-ordered content of files matched by inputFiles, but not in headerFiles or footerFiles
// - ordered content of the files in footerFiles
// - footer
```

Does this mean that if I have:

```
inputFiles: ['fileA', 'fileB']
```

The order of `fileA` and `fileB` in the final outputted file is not guaranteed?  If so, how can I guarantee the order is as specified in the `inputFiles` array?

**Comment by joliss** [comment]
I think you're asking this question on the wrong repo - maybe you meant https://github.com/ember-cli/broccoli-concat?

**Comment by khirakawa** [comment]
@joliss wow, that's quite embarrassing...!
