### ISSUE TITLE
EEXIST when a directory is created in two different input trees

### ISSUE THREAD

**Issue by dfreeman** [broccolijs/broccoli-merge-trees#50]
This is coming from https://github.com/ember-cli/ember-cli/issues/6236, which ultimately turned out to be an issue in broccoli-merge-trees.

When a directory with the same name is added at different times in two different input trees, the plugin ends up attempting to create a symlink where one already exists, resulting in an error like:

```
Error: EEXIST: file already exists, symlink '/Users/dfreeman/Desktop/broccoli-merge-failure/tmp/one/subdir/file1' -> '/var/folders/5x/vrw_v2r16vj3mftgg0h5_4640000gn/T/broccoli-96844FC3ATB2dAD1S/out-2-broccoli_merge_trees/subdir/file1'
```

A small reproduction of the issue (as minimal as I could come up with) is available here:
https://github.com/dfreeman/broccoli-merge-failure/blob/master/index.js

**Comment by stefanpenner** [comment]
thanks, will add this to the queue.

**Comment by stefanpenner** [comment]
@krisselden believes it may be related to: https://github.com/broccolijs/broccoli-merge-trees/blob/master/index.js#L296 becoming true / false given a change.

**Comment by nightire** [comment]
Really need this fixed, annoying. 🏌️

**Comment by hjdivad** [comment]
@nightire if you have the cycles to help, a PR with just a failing test for the issue would be awesome

**Comment by stefanpenner** [comment]
fix to the above issue is out:

* released as: `broccoli-merge-trees@v1.1.5`
* fix in fs-tree-diff: https://github.com/stefanpenner/fs-tree-diff/commit/cb0f4315a0790e094155969b7ea6c057e09b5358
* fix in this repo: https://github.com/broccolijs/broccoli-merge-trees/commit/c9b5054b6b5277c81dfd6961d9c06bd6f3437bd8

@dfreeman your reproduction was fantastic, has been [incorporated into the test suite](https://github.com/broccolijs/broccoli-merge-trees/blob/master/test.js#L59-L104) and lets us resolve the issue within an hour.

**Comment by hjdivad** [comment]
Strong 👍 on how good @dfreeman's fail case reproduction was.

**Comment by dfreeman** [comment]
Awesome—thanks so much for getting the fix out!
