### ISSUE TITLE
`.DS_Store` + `overwrite: false` results in sadness

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-merge-trees#53]
```js
Getting :  [BroccoliMergeTrees] failed with:
Error: Merge error: file modules/profile/templates/.DS_Store exists in /Users/segupta/Dev/copy/voyager-web_trunk/tmp/broccoli_merge_trees-input_base_path-gSVm96mm.tmp/0 and /Users/segupta/Dev/copy/voyager-web_trunk/tmp/broccoli_merge_trees-input_base_path-gSVm96mm.tmp/1
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
``` 

Should we consider auto-ignoring this one? Is that a bad path to go down?

Anecdotally this is just mega annoying for OSX users, and with a small adjustment on our side it could become a non-problem.

---

Questions: Is this a one-time thing, or will there be more. If we decide this is appropriate, by what criteria do we accept/decline additions to this set.

**Comment by rwjblue** [comment]
>  Is that a bad path to go down?

I fear this for exactly that reason.  There are a very large number of random editor swap files, OS plugin tmp files, etc...

**Comment by stefanpenner** [comment]
@rwjblue maybe the error needs to be more actionable. It is hard to connect problem/solution here, unsure how to improve this.

**Comment by joliss** [comment]
I wonder if tooling like Ember CLI should add a pre-process step on every input dir to strip out junk like .DS_Store? So the stripping only happens once at the beginning, not in the middle of the pipeline.

**Comment by stefanpenner** [comment]
@joliss today, we benefit from leaving large pieces of the tree "untouched/traversed" early in the pipeline, doing a pre-process step would impede that.

I'll find some time to give a more detailed example

**Comment by hjdivad** [comment]
@stefanpenner once we have change tracking and provide our own fs facade, it would be trivial to implement a `.brocignore` similar to what @joliss is suggesting.

In the meantime I share @rwjblue's fear.

**Comment by stefanpenner** [comment]
> @stefanpenner once we have change tracking and provide our own fs facade, it would be trivial to implement a .brocignore similar to what @joliss is suggesting.

Yes totally.

**Comment by stefanpenner** [comment]
As an interim step, should we detect this type of case and provide a more contextual error message?

**Comment by rwjblue** [comment]
> As an interim step, should we detect this type of case and provide a more contextual error message? 

Seems reasonable to detect a few well known scenarios and provide a customized error message, though I think that it will ultimately end up in a similar place to my original concern (and we will just keep building an ever growing list of patterns/values for the error).  No objection to this though, we just need to keep the bar relatively high for what ends up in this list...

**Comment by stefanpenner** [comment]
@rwjblue i suspect a slight rephrase for `.dofiles` will be sufficient.

**Comment by joliss** [comment]
Just spitballing: Maybe another solution is, avoid merging raw source directories, and instead try to only ever merge stuff after you've picked out the files you want, e.g. `**/*.js`. (I have no idea if this is feasible.)

**Comment by chipperatkins** [comment]
What are the steps to fix this for the unlucky OS X user (like me)?
