### ISSUE TITLE
release 1.2.2 appears broken

### ISSUE THREAD

**Issue by kellyselden** [broccolijs/broccoli-merge-trees#58]
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

https://travis-ci.org/kellyselden/ember-cli-node-modules-to-vendor/jobs/207119146
https://travis-ci.org/kellyselden/ember-datetimepicker/jobs/207119085
https://travis-ci.org/ember-cli/ember-cli/jobs/207118973

**Comment by steveax** [comment]
Yep, experiencing that here too.

**Comment by kellyselden** [comment]
This is resolved in v1.2.3. Although, this appears to be the first release that doesn't work with node v0.12. So if your CI is still running that, it still isn't going to work.

**Comment by joliss** [comment]
Thanks for reporting! CI should be green now as well.

Btw, I hope it was OK to drop 0.12 compatibility in a patch release. If this causes issues somewhere, please do let me know and I might bump the major (or minor?) in other packages in the future.

**Comment by tomreid76** [comment]
So this is technically a breaking change, because a legacy system of ours running node 0.12.x suddenly stopped working. Please use semver responsibly.

**Comment by tomreid76** [comment]
Nevermind, just had to specify `1.2.1` in my main package so that all these ember-cli deps use that one instead of matching on `^1.x.x`

**Comment by joliss** [comment]
> IMO, there should be a 1.2.4 release that rolls back to the 1.2.1 state and then introduce this new dependency merge-trees which forces the requirement of Node 4.x, in a major bump to 2.0.0.

Yup, you're right. I just went ahead and did exactly that :)

> I now have to go through 50+ places in the node_modules folder that include this package using a ^, update them, and then try generating a shrinkwrap to get around this.

If this sort of thing happens in the future: Yarn with its new yarn.lock file might also help with cases like this as well.

**Comment by tomreid76** [comment]
Great! Thank you. 

Yarn would not run in this project. It is a relatively stable legacy production app that is running on old node and mostly out of date dependencies. Just have to fix minor bugs and keep it building until we can push out the new shiny. :)

That said, as mentioned I was able to lock this dependency down by declaring it as a direct dependency (instead of 2 and 3 layers down) and we were green.
