### ISSUE TITLE
Minor version update includes breaking changes

### ISSUE THREAD

**Issue by K-Fitzpatrick** [broccolijs/broccoli-merge-trees#59]
Since version `1.2.2` and `1.2.3` include breaking changes (no longer supports `node<4.0` for example), should this be considered a major version change to `2.0.0`?

A little context: our enterprise app is locked into an old version of ember-cli (1.13.8), which depends on this via `^1.x.x`. A fresh `npm install` last night picked up the `SyntaxError: Unexpected reserved word`  on `class MergeTrees` error that was breaking the `broccoli-merge-trees` [travis builds](https://travis-ci.org/broccolijs/broccoli-merge-trees/builds/207118970).
Of course, if the project isn't following semantic versioning, feel free to close this.

**Comment by danwenzel** [comment]
Same here: https://travis-ci.org/sir-dunxalot/ember-new-relic/jobs/207503237

**Comment by joliss** [comment]
I just undid this change in v1.2.4, which should be Node 0.10-compatible again.

I also released broccoli-merge-trees v2.0.0, which now requires Node >= 4.

**Comment by danwenzel** [comment]
Upgrading to v1.2.4 fixed our issue.  Thanks!
